name: multi-example - e2e tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  pull-requests: read

jobs:
  run-playwright-tests:
    name: Playwright Tests
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Enable Corepack
        run: |
          corepack enable

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Install Chromium Browser
        run: yarn workspace @module-federation/vite exec playwright install --with-deps chromium

      - name: Build Projects
        run: yarn workspace @module-federation/vite build

      - name: Start Application multi-example
        run: nohup yarn workspace @module-federation/vite run multi-example & yarn workspace @module-federation/vite exec wait-on http://localhost:5173;

      - name: Run Playwright Tests
        run: yarn workspace @module-federation/vite exec playwright test

      - name: Upload Artifacts on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: reports/e2e/output
          retention-days: 3
