// Generated by scripts/generate-factory-files.ts — edit sharedDeps.ts gen config to update
export function mspUiCommonContextsExportCode(): string {
  return `
    const fallbackCandidates = typeof fallbackModule !== 'undefined' ? [
      fallbackModule,
      fallbackModule?.default,
    ] : [];

    const candidates = [
      moduleFactory,
      moduleFactory?.default,
      ...fallbackCandidates,
    ];

    const pick = (key) => {
      for (const candidate of candidates) {
        if (candidate && candidate[key] !== undefined) {
          return candidate[key];
        }
      }
      return undefined;
    };

    const sharedModule = pick('UiEventProvider')
      ? candidates.find((c) => c && c.UiEventProvider)
      : (moduleFactory?.default ?? moduleFactory);
    export default sharedModule;
    export const ActivityDispatchContext = pick('ActivityDispatchContext');
    export const ActivityDispatchProvider = pick('ActivityDispatchProvider');
    export const ActivityEvents = pick('ActivityEvents');
    export const DataCacheContext = pick('DataCacheContext');
    export const DataCacheEvents = pick('DataCacheEvents');
    export const DataCacheProvider = pick('DataCacheProvider');
    export const EventMessageTypeMapping = pick('EventMessageTypeMapping');
    export const MenuDispatchContext = pick('MenuDispatchContext');
    export const MenuDispatchProvider = pick('MenuDispatchProvider');
    export const MenuEvents = pick('MenuEvents');
    export const PresentationDispatchContext = pick('PresentationDispatchContext');
    export const PresentationDispatchProvider = pick('PresentationDispatchProvider');
    export const UiContentContext = pick('UiContentContext');
    export const UiContentProvider = pick('UiContentProvider');
    export const UiEventContext = pick('UiEventContext');
    export const UiEventProvider = pick('UiEventProvider');
    export const UserSessionContext = pick('UserSessionContext');
    export const UserSessionEvents = pick('UserSessionEvents');
    export const UserSessionProvider = pick('UserSessionProvider');
    export const useActivityDispatch = pick('useActivityDispatch');
    export const useDataCacheContext = pick('useDataCacheContext');
    export const useDataDispatch = pick('useDataDispatch');
    export const useEventContext = pick('useEventContext');
    export const useMenuDispatch = pick('useMenuDispatch');
    export const usePresentationBladeState = pick('usePresentationBladeState');
    export const usePresentationDispatch = pick('usePresentationDispatch');
    export const useUiEventContext = pick('useUiEventContext');
    export const useUiEventPublisher = pick('useUiEventPublisher');
    export const useUserSessionContext = pick('useUserSessionContext');
  `;
}
