// Generated by scripts/generate-factory-files.ts — edit sharedDeps.ts gen config to update
export function mspUiCommonExportCode(): string {
  return `
    const fallbackCandidates = typeof fallbackModule !== 'undefined' ? [
      fallbackModule,
      fallbackModule?.default,
    ] : [];

    const candidates = [
      moduleFactory,
      moduleFactory?.default,
      ...fallbackCandidates,
    ];

    const pick = (key) => {
      for (const candidate of candidates) {
        if (candidate && candidate[key] !== undefined) {
          return candidate[key];
        }
      }
      return undefined;
    };

    const sharedModule = pick('Re')
      ? candidates.find((c) => c && c.Re)
      : (moduleFactory?.default ?? moduleFactory);
    export default sharedModule;
    export const ActivityDispatchProvider = pick('ActivityDispatchProvider');
    export const Behaviour = pick('Behaviour');
    export const BehaviourDispatchProvider = pick('BehaviourDispatchProvider');
    export const BehaviourHandlerRegistryProvider = pick('BehaviourHandlerRegistryProvider');
    export const DataCacheProvider = pick('DataCacheProvider');
    export const MenuDispatchProvider = pick('MenuDispatchProvider');
    export const PresentationDispatchProvider = pick('PresentationDispatchProvider');
    export const PresetBooleanComponent = pick('PresetBooleanComponent');
    export const PresetDateComponent = pick('PresetDateComponent');
    export const PresetMoneyComponent = pick('PresetMoneyComponent');
    export const PresetNumberComponent = pick('PresetNumberComponent');
    export const PresetTextComponent = pick('PresetTextComponent');
    export const Re = pick('Re');
    export const ServiceDispatcher = pick('ServiceDispatcher');
    export const UiEventProvider = pick('UiEventProvider');
    export const createBehaviour = pick('createBehaviour');
    export const eventTypes = pick('eventTypes');
    export const useActivityDispatch = pick('useActivityDispatch');
    export const useBehaviourHandlerRegistry = pick('useBehaviourHandlerRegistry');
    export const useDataCache = pick('useDataCache');
    export const useDataCacheContext = pick('useDataCacheContext');
    export const useDataDispatch = pick('useDataDispatch');
    export const useMenuDispatch = pick('useMenuDispatch');
    export const usePresentationDispatch = pick('usePresentationDispatch');
    export const useUiEventContext = pick('useUiEventContext');
    export const useUiEventPublisher = pick('useUiEventPublisher');
    export const useUserSession = pick('useUserSession');
  `;
}
