// Generated by scripts/generate-factory-files.ts — edit sharedDeps.ts gen config to update
import { defaultExportCode } from './defaultExport';

export function muiMaterialExportCode(): string {
  return defaultExportCode();
}
