// Generated by scripts/generate-factory-files.ts — edit sharedDeps.ts gen config to update
export function reactDomExportCode(): string {
  return `
    const fallbackCandidates = typeof fallbackModule !== 'undefined' ? [
      fallbackModule,
      fallbackModule?.default,
    ] : [];

    const candidates = [
      moduleFactory,
      moduleFactory?.default,
      ...fallbackCandidates,
    ];

    const pick = (key) => {
      for (const candidate of candidates) {
        if (candidate && candidate[key] !== undefined) {
          return candidate[key];
        }
      }
      return undefined;
    };

    const sharedModule = pick('createPortal')
      ? candidates.find((c) => c && c.createPortal)
      : (moduleFactory?.default ?? moduleFactory);
    export default sharedModule;
    export const createPortal = pick('createPortal');
    export const flushSync = pick('flushSync');
    export const unstable_batchedUpdates = pick('unstable_batchedUpdates');
    export const version = pick('version');
  `;
}
