// Generated by scripts/generate-factory-files.ts — edit sharedDeps.ts gen config to update
export function reactJsxDevRuntimeExportCode(): string {
  return `
    const fallbackCandidates = typeof fallbackModule !== 'undefined' ? [
      fallbackModule,
      fallbackModule?.default,
    ] : [];

    const candidates = [
      moduleFactory,
      moduleFactory?.default,
      ...fallbackCandidates,
    ];

    const pick = (key) => {
      for (const candidate of candidates) {
        if (candidate && candidate[key] !== undefined) {
          return candidate[key];
        }
      }
      return undefined;
    };

    const sharedModule = pick('jsxDEV')
      ? candidates.find((c) => c && c.jsxDEV)
      : (moduleFactory?.default ?? moduleFactory);
    export default sharedModule;
    export const Fragment = pick('Fragment');
    export const jsxDEV = pick('jsxDEV');
  `;
}
