// Generated by scripts/generate-factory-files.ts — edit sharedDeps.ts gen config to update
export function semverExportCode(): string {
  return `
    const fallbackCandidates = typeof fallbackModule !== 'undefined' ? [
      fallbackModule,
      fallbackModule?.default,
    ] : [];

    const candidates = [
      moduleFactory,
      moduleFactory?.default,
      ...fallbackCandidates,
    ];

    const pick = (key) => {
      for (const candidate of candidates) {
        if (candidate && candidate[key] !== undefined) {
          return candidate[key];
        }
      }
      return undefined;
    };

    const sharedModule = pick('satisfies')
      ? candidates.find((c) => c && c.satisfies)
      : (moduleFactory?.default ?? moduleFactory);
    export default sharedModule;
    export const gt = pick('gt');
    export const satisfies = pick('satisfies');
  `;
}
