// ===================================================================
// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// ===================================================================
// Generated by: scripts/generate-extension-types.ts
// Generated at: 2026-06-07T11:41:44.934Z
// 
// This file provides CNTX type substitution for extension interfaces.
// Extension interfaces are defined with placeholder types at component
// definition time, but need concrete CNTX instances when builders are
// created. The ExtensionOf type performs this substitution.
//
// To regenerate: npm run generate:extension-types
//
// Detected extensions:
//   - SingleItemContainerExtension
//   - ElementSetContainerExtension
//   - TableExtension
//   - StepperExtension
// ===================================================================

import type { ComponentWrapper } from '../components/ReComponentWrapper.js';
import type { 
  CNTX,
  ReUiPlanComponentBuilder,
  ReBuilderBase, 
  FluentSimple,
  FluentSubBuilder
} from './ReUiPlanBuilder.js';

import {SingleItemContainerExtension, SimplifiedReUiPlanComponentBuilder, ElementSetContainerExtension, ReUiPlanElementSetBuilder} from '../components/ContainerElements.js';
import {TableExtension, ColumnBuilder, FilterBuilder} from '../../components/tables/tableTypes.js';
import {StepperExtension, StepperPageBuilder} from '../../components/containers/stepper.js';

/**
 * Maps extension methods to properly substitute CNTX and RT types.
 * Handles: SingleItemContainerExtension, ElementSetContainerExtension, TableExtension, StepperExtension
 */
export type ExtensionOf<C extends CNTX, T extends ComponentWrapper<any, any>, _BLD = unknown, RT = any> =
  T extends ComponentWrapper<infer _P, infer E>
    ? E extends object
      ?   // Handle SingleItemContainerExtension
         E extends SingleItemContainerExtension<any, any>
         ? { [K in keyof E]:
             // calculate the new return type
             E[K] extends ((...args: infer A) => infer R) // check for functions
               //  we are a function
               ? R extends FluentSimple  //check for simple pattern #1
                 // yes we are simple pattern #1
                 ? ((...args: A) => ComponentBuilderWithExt<C, T, RT> & SingleItemContainerExtension<C, RT>)
                 // not simple pattern #1, check for pattern #2
                 : R extends FluentSubBuilder<infer BLD2> // check for sub-builder pattern #2
                   ? BLD2 extends SimplifiedReUiPlanComponentBuilder<any, any>
                     ? ((...args: A) => SimplifiedReUiPlanComponentBuilder<C, ComponentBuilderWithExt<C, T, RT>>)
                     : E[K]
                   : E[K] // not pattern #2 either
               // we are not a function
               : E[K]
           }
       // Handle ElementSetContainerExtension
      :  E extends ElementSetContainerExtension<any, any>
         ? { [K in keyof E]:
             // calculate the new return type
             E[K] extends ((...args: infer A) => infer R) // check for functions
               //  we are a function
               ? R extends FluentSimple  //check for simple pattern #1
                 // yes we are simple pattern #1
                 ? ((...args: A) => ComponentBuilderWithExt<C, T, RT> & ElementSetContainerExtension<C, RT>)
                 // not simple pattern #1, check for pattern #2
                 : R extends FluentSubBuilder<infer BLD2> // check for sub-builder pattern #2
                   ? BLD2 extends ReUiPlanElementSetBuilder<any, any>
                     ? ((...args: A) => ReUiPlanElementSetBuilder<C, ComponentBuilderWithExt<C, T, RT>>)
                     : E[K]
                   : E[K] // not pattern #2 either
               // we are not a function
               : E[K]
           }
       // Handle TableExtension
      :  E extends TableExtension<any, any>
         ? { [K in keyof E]:
             // calculate the new return type
             E[K] extends ((...args: infer A) => infer R) // check for functions
               //  we are a function
               ? R extends FluentSimple  //check for simple pattern #1
                 // yes we are simple pattern #1
                 ? ((...args: A) => ComponentBuilderWithExt<C, T, RT> & TableExtension<C, RT>)
                 // not simple pattern #1, check for pattern #2
                 : R extends FluentSubBuilder<infer BLD2> // check for sub-builder pattern #2
                   ? BLD2 extends ColumnBuilder<any, any>
                     ? ((...args: A) => ColumnBuilder<C, ComponentBuilderWithExt<C, T, RT>>)
                   : BLD2 extends FilterBuilder<any, any>
                     ? ((...args: A) => FilterBuilder<C, ComponentBuilderWithExt<C, T, RT>>)
                     : E[K]
                   : E[K] // not pattern #2 either
               // we are not a function
               : E[K]
           }
       // Handle StepperExtension
      :  E extends StepperExtension<any, any>
         ? { [K in keyof E]:
             // calculate the new return type
             E[K] extends ((...args: infer A) => infer R) // check for functions
               //  we are a function
               ? R extends FluentSimple  //check for simple pattern #1
                 // yes we are simple pattern #1
                 ? ((...args: A) => ComponentBuilderWithExt<C, T, RT> & StepperExtension<C, RT>)
                 // not simple pattern #1, check for pattern #2
                 : R extends FluentSubBuilder<infer BLD2> // check for sub-builder pattern #2
                   ? BLD2 extends StepperPageBuilder<any, any>
                     ? ((...args: A) => StepperPageBuilder<C, ComponentBuilderWithExt<C, T, RT>>)
                     : E[K]
                   : E[K] // not pattern #2 either
               // we are not a function
               : E[K]
           }
      : E  // Fallback: not a recognized extension, return as-is
    : E
  : never;


export type ReturnTypeOf<R> =
  R extends ReBuilderBase<any> ? (R extends ReBuilderBase<infer RT> ? RT : never) : never;


// Re-export for convenience
export type ComponentBuilderWithExt<C extends CNTX, T extends ComponentWrapper<any, any>, RT> = 
  ReUiPlanComponentBuilder<C, T, RT> & ExtensionOf<C, T, ReUiPlanComponentBuilder<C, T, RT>, RT>;
