#!/usr/bin/env node

import { existsSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { generateKeyPairSync, createPublicKey, randomUUID } from 'node:crypto';

function parseArgs(argv) {
  const args = {
    out: '.env.generated.keys',
    force: false,
    inUseSuffix: '1',
  };

  for (let i = 0; i < argv.length; i += 1) {
    const current = argv[i];
    if (current === '--out' && argv[i + 1]) {
      args.out = argv[i + 1];
      i += 1;
      continue;
    }
    if (current === '--force') {
      args.force = true;
      continue;
    }
    if (current === '--in-use-suffix' && argv[i + 1]) {
      const suffix = argv[i + 1] === '2' ? '2' : '1';
      args.inUseSuffix = suffix;
      i += 1;
      continue;
    }
  }

  return args;
}

function generateKeySet(suffix) {
  const { privateKey, publicKey } = generateKeyPairSync('rsa', {
    modulusLength: 2048,
    publicKeyEncoding: { type: 'spki', format: 'pem' },
    privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
  });

  const kid = `msp-security-kid-${suffix}-${randomUUID()}`;

  const jwk = createPublicKey(publicKey).export({ format: 'jwk' });
  const encryptionPublicKey = {
    kid,
    kty: 'RSA',
    alg: 'RSA-OAEP-256',
    use: 'enc',
    n: jwk.n,
    e: jwk.e,
    key_ops: ['encrypt'],
  };

  return {
    suffix,
    kid,
    privateKeyPem: privateKey,
    encryptionPublicKey,
  };
}

function asSingleQuotedValue(value) {
  return `'${value.replace(/'/g, "'\\''")}'`;
}

function buildEnvText(keySet1, keySet2, inUseSuffix) {
  const keySets = [keySet1, keySet2];

  const lines = [];
  lines.push('# Generated by scripts/generateSecurityKeyEnv.mjs');
  lines.push(`# Generated at ${new Date().toISOString()}`);
  lines.push('# Do not commit this file.');
  lines.push('');
  lines.push(`# Active keyset suffix used by msp_security key resolution: 1 or 2`);
  lines.push(`MSP_SECURITY_IN_USE_SUFFIX=${inUseSuffix}`);
  lines.push('');

  for (const set of keySets) {
    const suffix = set.suffix;
    const privateKeysJson = JSON.stringify([
      {
        kid: set.kid,
        privateKeyPem: set.privateKeyPem,
      },
    ]);
    const publicKeyJson = JSON.stringify(set.encryptionPublicKey);

    lines.push(`# --- Keyset ${suffix} ---`);
    lines.push(`MSP_SECURITY_DEFAULT_KID_${suffix}=${set.kid}`);
    lines.push(`MSP_SECURITY_DEFAULT_PRIVATE_KEY_PEM_${suffix}=${asSingleQuotedValue(set.privateKeyPem)}`);
    lines.push(`MSP_SECURITY_PRIVATE_KEYS_JSON_${suffix}=${asSingleQuotedValue(privateKeysJson)}`);
    lines.push(`MSP_SECURITY_ENCRYPTION_PRIVATE_KEY_PEM_${suffix}=${asSingleQuotedValue(set.privateKeyPem)}`);
    lines.push(`MSP_SECURITY_ENCRYPTION_PUBLIC_KEY_JSON_${suffix}=${asSingleQuotedValue(publicKeyJson)}`);
    lines.push('');
  }

  lines.push('# Optional legacy fallback values (kept aligned with keyset 1)');
  lines.push(`MSP_SECURITY_DEFAULT_KID=${keySet1.kid}`);
  lines.push(`MSP_SECURITY_DEFAULT_PRIVATE_KEY_PEM=${asSingleQuotedValue(keySet1.privateKeyPem)}`);
  lines.push(`MSP_SECURITY_PRIVATE_KEYS_JSON=${asSingleQuotedValue(JSON.stringify([{ kid: keySet1.kid, privateKeyPem: keySet1.privateKeyPem }]))}`);
  lines.push(`MSP_SECURITY_ENCRYPTION_PRIVATE_KEY_PEM=${asSingleQuotedValue(keySet1.privateKeyPem)}`);
  lines.push(`MSP_SECURITY_ENCRYPTION_PUBLIC_KEY_JSON=${asSingleQuotedValue(JSON.stringify(keySet1.encryptionPublicKey))}`);
  lines.push('');

  return `${lines.join('\n')}\n`;
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const outPath = resolve(process.cwd(), args.out);

  if (!args.force && existsSync(outPath)) {
    console.error(`Refusing to overwrite existing file: ${outPath}`);
    console.error('Re-run with --force to overwrite, or pass --out <path>.');
    process.exit(1);
  }

  const keySet1 = generateKeySet('1');
  const keySet2 = generateKeySet('2');
  const content = buildEnvText(keySet1, keySet2, args.inUseSuffix);

  writeFileSync(outPath, content, 'utf8');

  console.log(`Generated security key env file: ${outPath}`);
  console.log('Next steps:');
  console.log(`  1) Review ${args.out}`);
  console.log(`  2) Copy values into your runtime env source`);
  console.log('  3) Keep this file out of source control');
}

main();
